// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CarregarSaves() {
  return window['go']['main']['App']['CarregarSaves']();
}

export function DeletarDiretorios() {
  return window['go']['main']['App']['DeletarDiretorios']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Inicializar() {
  return window['go']['main']['App']['Inicializar']();
}

export function ListaDiretorios() {
  return window['go']['main']['App']['ListaDiretorios']();
}
