// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CarregarSaves() {
  return window['go']['main']['App']['CarregarSaves']();
}

export function CriarBackup(arg1) {
  return window['go']['main']['App']['CriarBackup'](arg1);
}

export function DeletarDiretorios() {
  return window['go']['main']['App']['DeletarDiretorios']();
}

export function Inicializar() {
  return window['go']['main']['App']['Inicializar']();
}

export function TornarAtivo(arg1) {
  return window['go']['main']['App']['TornarAtivo'](arg1);
}
