// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CarregarSaves():Promise<Array<main.Save>>;

export function CriarBackup(arg1:string):Promise<boolean>;

export function DeletarDiretorios():Promise<boolean>;

export function Inicializar():Promise<boolean>;

export function TornarAtivo(arg1:string):Promise<boolean>;
